<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Python_Data_Analytics_Course/blob/main/4_Problems/2_07_Pandas Merge DataFrames.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

## 🟩 Merge US Jobs and Monthly Postings (2.7.1)

In [13]:
# df_US = df[df['job_location'] == 'United States']
# df['job_posted_date']=df['job_posted_date'].dt.to_period('M')
# df_monthly_postings = df_US.groupby('job_posted_month').size().reset_index(name='job_postings')
# df_monthly = pd.DataFrame(df_monthly_postings)
# df_merged = df_US.merge(df_monthly, on='job_posted_month', how='right')
df['job_posted_month'] = df['job_posted_date'].dt.to_period('M')
df_us_jobs = df[df['job_country'] == 'United States']
df_monthly_postings = df_us_jobs.groupby('job_posted_month').size().reset_index(name='postings_count')
merged_df = pd.merge(df_us_jobs, df_monthly_postings, on='job_posted_month', how='right')
merged_df.head()

AttributeError: 'PeriodProperties' object has no attribute 'to_period'

---

## 🟨 Merge Non-Remote Jobs and Salary (2.7.2)

In [22]:
df_not_remote_jobs = df[df['job_work_from_home'] == False]
df_not_remote_salary = df_not_remote_jobs.groupby('job_title_short')['salary_year_avg'].mean()
df_not_remote_salary =pd.DataFrame(df_not_remote_salary)
df_not_remote_jobs.merge(df_not_remote_salary, on='job_title_short', how='right').head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg_x,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_avg_y
0,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06,False,False,Denmark,NaN,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow...",90177.41994
1,Business Analyst,Business Intelligence Intern,"Dallas, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01,False,False,United States,NaN,NaN,NaN,Copart,"['r', 'python', 'sql', 'tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi'], 'pr...",90177.41994
2,Business Analyst,BI Engineer,Namibia,via Intellijobs.ai,Full-time,False,Namibia,2023-03,False,False,Namibia,NaN,NaN,NaN,Innover,"['sql', 'gcp', 'looker', 'tableau']","{'analyst_tools': ['looker', 'tableau'], 'clou...",90177.41994
3,Business Analyst,Business Analyst,"Tel Aviv-Yafo, Israel",via Comeet,Full-time,False,Israel,2023-09,False,False,Israel,NaN,NaN,NaN,ironSource,"['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",90177.41994
4,Business Analyst,Commercial Analyst,South Africa,via LinkedIn,Full-time,False,South Africa,2023-02,True,False,South Africa,NaN,NaN,NaN,PEP,"['sql', 'tableau', 'spss', 'sap']","{'analyst_tools': ['tableau', 'spss', 'sap'], ...",90177.41994

---

## 🟨 Merge Company Salary and Remote Count (2.7.3)

In [34]:
df_company_salary = df.groupby('company_name')['salary_year_avg'].mean()
df_company_remote = df[df['job_work_from_home'] == True].groupby('company_name').size()
df_company_remote = pd.DataFrame(df_company_remote)
df_company_salary = pd.DataFrame(df_company_salary)
df_company_remote_merged = df_company_salary.merge(df_company_remote, on='company_name', how='inner')
df_company_remote_merged.head(5)

                                           salary_year_avg  0
company_name
#EqualsTrue                                            NaN  4
#TeamGoHealth                                          NaN  1
#twiceasnice Recruiting                            77750.0  1
&Work                                                  NaN  1
(AEG) Application Engineering Group, Inc.              NaN  1

---